[workspace]
authors = ["Alex Nilles <nillesa2@wwu.edu>"]
channels = ["conda-forge"]
name = "IK-497"
platforms = ["linux-64"]
preview = ["pixi-build"]
version = "0.1.0"

[package]
name = "497_ikpy"
version = "0.1.0"

[package.build.backend]
name = "pixi-build-python"
version = "*"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[tasks]
kernel = "python -m ipykernel install --user --name 497_kernel --display-name \"497 Kernel\""
clean = "rm *.URDF *.ipynb"
setup = {cmd = ["echo", "Finished setup!"], depends-on = ["kernel"]}

[dependencies]
jupyterlab = ">=4.5.2,<5"
ipykernel = ">=7.1.0,<8"
ipympl = ">=0.9.8,<0.10"
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
scipy = ">=1.17.0,<2"
pyglet = "<2"

[pypi-dependencies]
ikpy = { git = "https://github.com/AQNclasses/ikpy" }
yourdfpy = ">=0.0.59, <0.0.60"
